name: CodacyCoverageWorkflow

on:
  push:
    branches: [ main ]

jobs:
  generate-and-upload-coverage:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.6"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.15

      - name: Run setup
        run: |
          poetry install
          cp .env.sample .env

      - name: Generate coverage
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/generate_coverage.sh
          sh $GITHUB_WORKSPACE/scripts/generate_coverage.sh

      - name: Upload coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: $GITHUB_WORKSPACE/coverage.xml

